name: Check for New Releases

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12pm UTC
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Optional: Fetches all history for all branches

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run update script for CoolerControl
      run: |
        python3 .github/scripts/update_from_releases.py --repo guniv/CoolerControl-Docker --xml CoolerControl.xml --last .last_release_coolercontrol
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run update script for Jellyfin-Newsletter
      run: |
        python3 .github/scripts/update_from_releases.py --repo SeaweedbrainCY/jellyfin-newsletter --xml Jellyfin-Newsletter.xml --last .last_release_jellyfin_newsletter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add CoolerControl.xml Jellyfin-Newsletter.xml .last_release_coolercontrol .last_release_jellyfin_newsletter
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "Update to latest release(s)"
          git push
        )
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
